/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package binarytree;

import java.util.ArrayList;
import java.util.Random;
import java.util.Scanner;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Anthony Scully
 */
public class GUI extends javax.swing.JDialog {

    private static MyTree tree;
    private static final ArrayList<String> data = new ArrayList<>();
    private static MyLinkedList linkedList;

    /**
     * Creates new form GUI
     */
    public GUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadDataToArrayList();
        loadLinkedList();
    }

    /* Loads from the csv file into the arraylist */
    private void loadDataToArrayList() {
        Scanner sc = new Scanner(CommandGUI.class.getResourceAsStream("Test-Data.csv"));
        sc.nextLine();
        while (sc.hasNextLine()) {
            data.add(sc.nextLine());
        }
    }

    /* Loads data from arraylist to the linked list.*/
    private void loadLinkedList() {
        linkedList = new MyLinkedList();
        for (String s : data) {
            String lineData[] = s.split(",");
            linkedList.addNode(new LinkedListNode(Integer.parseInt(lineData[0]),
                    lineData[1], Double.parseDouble(lineData[2])));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonAdd = new javax.swing.JButton();
        buttonSearch = new javax.swing.JButton();
        buttonRemove = new javax.swing.JButton();
        buttonPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buttonAdd.setText("Add");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        buttonSearch.setText("Search");
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });

        buttonRemove.setText("Remove");
        buttonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveActionPerformed(evt);
            }
        });

        buttonPrint.setText("Print");
        buttonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(buttonAdd)
                .addGap(18, 18, 18)
                .addComponent(buttonRemove)
                .addGap(18, 18, 18)
                .addComponent(buttonSearch)
                .addGap(26, 26, 26)
                .addComponent(buttonPrint)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(244, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAdd)
                    .addComponent(buttonSearch)
                    .addComponent(buttonRemove)
                    .addComponent(buttonPrint))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        // Creates the input bpx
        JTextField itemRef = new JTextField(20);
        JTextField itemDesc = new JTextField(20);
        JTextField itemPrice = new JTextField(20);
        
        JPanel p = new JPanel();
        p.add(new JLabel("Reference No: "));
        p.add(itemRef);
        p.add(Box.createHorizontalStrut(15));
        p.add(new JLabel("Description"));
        p.add(itemDesc);
        p.add(Box.createHorizontalStrut(15));
        p.add(new JLabel("Price"));
        p.add(itemPrice);
        
        int result = JOptionPane.showConfirmDialog(null, p, "Add an item",
                JOptionPane.OK_CANCEL_OPTION);
        
        int ref = Integer.parseInt(itemRef.getText());
        String description = itemDesc.getText();
        double price = Double.parseDouble(itemPrice.getText());
        
        if (result == JOptionPane.OK_OPTION) {
            linkedList.addNode(new LinkedListNode(ref, description, price));
        }
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPrintActionPerformed
        linkedList.printAllNodes();
    }//GEN-LAST:event_buttonPrintActionPerformed

    private void buttonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveActionPerformed
        JTextField itemRef = new JTextField(20);
        
        JPanel p = new JPanel();
        p.add(new JLabel("Reference No: "));
        p.add(itemRef);
        int result = JOptionPane.showConfirmDialog(null, p, "Add an item",
                JOptionPane.OK_CANCEL_OPTION);
        
        int ref = Integer.parseInt(itemRef.getText());
        
        if (result == JOptionPane.OK_OPTION) {
            linkedList.removeNode(ref);
        }
    }//GEN-LAST:event_buttonRemoveActionPerformed

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        JTextField itemRef = new JTextField(20);
        
        JPanel p = new JPanel();
        p.add(new JLabel("Reference No: "));
        p.add(itemRef);
        int result = JOptionPane.showConfirmDialog(null, p, "Add an item",
                JOptionPane.OK_CANCEL_OPTION);
        
        int ref = Integer.parseInt(itemRef.getText());
        
        if (result == JOptionPane.OK_OPTION) {
            System.out.println(linkedList.findNode(ref).toString());
        }
    }//GEN-LAST:event_buttonSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUI dialog = new GUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonPrint;
    private javax.swing.JButton buttonRemove;
    private javax.swing.JButton buttonSearch;
    // End of variables declaration//GEN-END:variables

}
